name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    # Define environment variables here for easy access
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_REPO }} # Make sure this secret is "username/repo-name"
      TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Tag Docker image with Git SHA
        run: |
          SHA_TAG=${GITHUB_SHA::8}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.IMAGE_NAME }}:$SHA_TAG

      - name: Push Docker images
        run: |
          SHA_TAG=${GITHUB_SHA::8}
          docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${{ env.IMAGE_NAME }}:$SHA_TAG
